services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_APP_ENVIRONMENT=${FASTAPI_APP_ENVIRONMENT:-dev}
      - SESSION_SECRET=${SESSION_SECRET}
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=${MONGO_DB_NAME:-dts2}
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:8.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-dts2}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:1.0
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USER:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASSWORD:-pass}
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
